[master]
master ansible_host=54.210.123.45 ansible_user=ubuntu

[workers]
worker1 ansible_host=3.15.44.120 ansible_user=ubuntu
worker2 ansible_host=18.199.65.10 ansible_user=ubuntu

[k8s_cluster:children]
master
workers